[versions]
node = "v16.14.0" # You can use any Node and NPM Version
# You can also specify the platform:
# node = { version = "v16.14.0", platform = "darwin-arm64" } 

[tasks.setup]
command = "npm i"

[tasks.dev]
command = "npm run dev"

[tasks.build]
command = "npm run build"

[tasks.version]
command = "node --version"

[tasks.test]
command = "npm run test"

[tasks.watch]
command = "npm run watch"

[tasks.start]
command = "npm run start"

[tasks.lint]
command = "eslint . --ext .js,.jsx,.ts,.tsx"

[tasks.deploy]
command = "npm run deploy"

[tasks.clean]
command = "rm -rf node_modules dist"
